### PR TITLE
Admin SDK User/Group/Member support and misc bug-fixes

### PR DESCRIPTION
**Pull request by jcwatson11**
Okay, lots of changes being submitted in this pull request.

The ngGAPI has now been updated and tested against the current google-provided javascript client, using OAuth2, and now supports the users, groups and members API's from the Admin SDK portion of the Google API.

Change Summary:

- Added API configs to support Admin Directory users, groups & members.
- Refactored OAuth2 wrapper and proved that it works in immediate=true mode.
- Updated existing unit tests to work with PhantomJS so it runs headless instead of in Chrome. (Feel free to change this back if you want)
- Added main: gapi.js to the bower file for better auto-injection support in other projects.
- Updated README.md file to include the fact that support for Admin SDK users, groups & members have been added.
- Changed references to console.log to $log.log so it doesn't break older versions of MSIE javascript.
- Fixed bug in cases where HTTP DELETE is called, where the transaction status could not be read by the caller to verify that the transaction succeeded. Google's API doesn't return any object when DELETE is successful, only a status code as part of the HTTP response. So the caller needs to have access to the transaction object, not just the expected response body object. (lines 133-136 in gapi.js)
- Added deferred.notify calls during OAuth2 process to help with communicating to the caller about what is happening during the OAuth2 process.
- The OAuth2 process will attempt login 4 times before sending deferred.reject.
- Cleaned up trailing white space throughout gapi.js and test spec files.
- Curly braces and white space changed to be more consistent with original code-style.

NOTE: When accessing any of the Admin SDK API's, (currently only users, groups and group members are supported), you need to do the following:

1. Access the Google Developer console and create an API Client ID for a Web Application. The interface keeps changing every few months, so hopefully the key words "Client ID, and Web Application" are enough to help you find what you're looking for. You want a key that allows you to restrict access by referrer domain name.

2. Log into your Google Apps domain account as an administrator. By the time you read this, the admin screen might have changed, but here's the path to what you need as of this writing:

Security -> Show More (at bottom) -> Advanced Settings -> Manage API client access

3. Once you're on that page, you need to enter your client ID and a comma-delimited list of scopes, as defined by the Admin SDK Documentation here: https://developers.google.com/admin-sdk/directory/v1/guides/authorizing

Once you have done that, you should be able to use your Client ID in your javascript call to the Google API as noted in the ngGAPI documentation that Christian wrote.

### CODE REVIEW

**Comment by christiansmith** [comment]
@jcwatson11 

Great work, thanks!

This is quite a lot in one PR. Would you mind doing a quick code review with me in a hangout before I merge?

**Comment by jcwatson11** [comment]
Yeah. It sure is. And sure. Let's hang... or whatever you call it on a Google hang-out. (I usually Skype).

Is there some way to send a private message through github so I can send you my contact details?

**Comment by christiansmith** [comment]
Email me. 
smith@anvil.io

**Comment by jcwatson11** [comment]
Hey Christian,

It was really good to meet, and talk with you during our code review. The changes you requested are committed in this pull request. Thanks for all your support. I look forward to working with you again in the future!

Jon

**Comment by christiansmith** [comment]
Thanks Jon! Enjoyed meeting you as well. Please stay in touch.

**Pull request merged**
